# Exercícios Módulo 5. Livrarias especializadas em dados (Soluções)

Considerações a ter em conta:

* Guardar este documento com o seguinte formato para entrega: __M5_05_nome_apelido1_apelido2__
* Fazer os exercícios com as ferramentas vistas nas sessões. 
* Comentar o código
* Utilizar nomes de variáveis apropriados, se vai guardar uma nota, chamar a essa variável nota, não n ou x

**1) Trabalhar com NumPy**

* Importar numpy e usar um alias para poder utilizar os seus recursos 
* Criar um array de elementos (de 10 a 100)
* Inverter o array
* Criar um array 3x3 com valores de 0 a 8 
* Criar um array identidade de 6x6
* Criar um array com valores aleatórios com o formato 3x3x3
* Criar dois arrays, com valores aleatórios, A e B, e verificar se são iguais (há várias opções, investigar)

In [16]:
# Completar o exercício aqui

import numpy as np  # Import NumPy and alias it as np

# Create an array of elements from 10 to 100
array_10_to_100 = np.arange(10, 101)

# Invert the array
inverted_array = np.flip(array_10_to_100)

# Create a 3x3 array with values from 0 to 8
array_3x3 = np.arange(9).reshape(3, 3)

# Create a 6x6 identity array
identity_array = np.eye(6)

# Create a 3x3x3 array with random values
random_array = np.random.rand(3, 3, 3)

# Create two random arrays, A and B
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

# Check if arrays A and B are equal (element-wise)
are_equal = np.array_equal(A, B)

print("Array from 10 to 100:")
print(array_10_to_100)
print("\nInverted Array:")
print(inverted_array)
print("\n3x3 Array:")
print(array_3x3)
print("\n6x6 Identity Array:")
print(identity_array)
print("\n3x3x3 Random Array:")
print(random_array)
print("\nArrays A and B are equal:", are_equal)

Array from 10 to 100:
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]

Inverted Array:
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]

3x3 Array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

6x6 Identity Array:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

3x3x3 Random Array:
[[[0.17268

**2) Seguir com NumPy**

* Criar um array de 100 elementos aleatórios compreendidos entre 1 e 1000 (podem ser números inteiros). 
* Este array irá chamar-se dólares
* Fazer a conversão dos preços em dólares do primeiro array para um segundo array que se vai chamar euros. Devemos utilizar a  seguinte conversão: 
  - 1 USD = 0,874413 EUR
* Mostrar o resultado do array de euros, arredondando a 2 casas decimais.

In [4]:
# Completar o exercício aqui
import numpy as np

# Create an array of 100 random elements between 1 and 1000
dolares = np.random.randint(1, 1001, 100)
print("Array of Prices in Dollars:")
print(dolares)

# Conversion rate
conversion_rate = 0.874413

# Convert dollars to euros
euros = dolares * conversion_rate

# Round the result to 2 decimal places
euros = np.round(euros, 2)

# Display the resulting array of euros
print("\nArray of Prices in Euros:")
print(euros)


Array of Prices in Dollars:
[242 578 423 177  87 130 909 525 927 681 932 940 227 995 380 670 391  67
  88 421 954 906 120 579  76  70 287 902 411 658 639 523 987 263 279 999
 134 219  84 344 923 155 565 321 128 704 754 336 152  81 746 417 507 311
 748 813 937 535  95 878  14 885 474  92 998  40 749 359 474 700 995  19
 341 904 390 230 611 861 260 980 606 610 704 502 420 787 455 534  93 196
 213 592 530 438 762 992 208 670 969 518]

Array of Prices in Euros:
[211.61 505.41 369.88 154.77  76.07 113.67 794.84 459.07 810.58 595.48
 814.95 821.95 198.49 870.04 332.28 585.86 341.9   58.59  76.95 368.13
 834.19 792.22 104.93 506.29  66.46  61.21 250.96 788.72 359.38 575.36
 558.75 457.32 863.05 229.97 243.96 873.54 117.17 191.5   73.45 300.8
 807.08 135.53 494.04 280.69 111.92 615.59 659.31 293.8  132.91  70.83
 652.31 364.63 443.33 271.94 654.06 710.9  819.32 467.81  83.07 767.73
  12.24 773.86 414.47  80.45 872.66  34.98 654.94 313.91 414.47 612.09
 870.04  16.61 298.17 790.47 341.02 201.11

**3) Trabalhar com pandas**

* Importar pandas e usar um alias para poder utilizar os seus recursos.
* Carregar como dataframe de pandas csv 05_05_imdb_títulos.csv e mostrar os seus 5 primeiros registos.
* Carregar como dataframe de pandas o csv 05_05_imdb_elenco.csv e mostrar os seus 5 primeiros registos
* Mostrar o número de registos do dataframe de títulos.
* Mostrar o número de registos do dataframe de elenco.
* Mostrar os 5 titulos mais antigas.
* Mostrar os filmes que no título contem a palavra “Drácula”. Quantos filmes são?
* Mostrar os 10 títulos mais comuns (que mais se repetem).
* Mostrar qual foi o primeiro filme chamado “Romeo and Juliet”.
* Listar todas os filmes que contenham a palavra “Exorcist”, ordenados do mais antigo ao mais recente.
* Mostrar quantos filmes foram feitas no ano 1950.
* Mostrar quantaos filmes foram feitas de 1950 a 1959 (inclusive).
* Mostrar todas os papéis que teve a trilogia “The Godfather”, agrupando pelo papel e forneca a informação da quantidade de vezes esse papel apareceu (exemplo: michael corleone aparece nos 3 filmes da triologia).
* Mostrar o elenco completo, ordenado pela classificação “n” do filme “Drácula” de 1958.
* Mostrar quantos papéis teve “Bruce Wayne” como protagonista (Dica: Em Batman de 1989, existe Bruce Wayne e tambem Young Bruce Wayne, que deverão ambos aparecer).
* Mostrar quantos papéis fez “Robert de Niro” na sua carreira.
* Listagem de papéis como protagonista (n=1) que teve o ator “Charlton Heston” na década dos 60’s, ordenado  por ano de forma descendente.
* Mostrar quantos papéis para atores teve na década 50’s.
* Mostrar quantos papéis para atrizes teve na década 50’s.

In [6]:
# Completar o exercício aqui

# Import pandas with an alias
import pandas as pd

# Set the maximum width to a larger value to avoid splitting the print
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 1000)

# Códigos para formatar o texto dos prints
class color:
    PURPLE = '\033[95m'
    CYAN = '\033[96m'
    DARKCYAN = '\033[36m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    WHITE = '\033[97m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    END = '\033[0m'
    REDBACK = '\033[41m'
    REVERSE = '\u001b[7m'

# Load the CSV files into DataFrames
titles_df = pd.read_csv('05_05_imdb_titulos.csv')
elenco_df = pd.read_csv('05_05_imdb_elenco.csv')

# Show the first 5 records of each DataFrame
print(color.REVERSE + color.BOLD + "First 5 records of titles_df:" + color.END)
print(titles_df.head())
print()
print(color.REVERSE + color.BOLD + "First 5 records of elenco_df:" + color.END)
print(elenco_df.head())

# Show the number of records in each DataFrame
print(color.REVERSE + color.BOLD + "\nNumber of records in titles_df:" + color.END, len(titles_df))
print(color.REVERSE + color.BOLD + "Number of records in elenco_df:" + color.END, len(elenco_df))

# Show the 5 oldest titles
oldest_titles = titles_df.sort_values(by='year').head()
print(color.REVERSE + color.BOLD + "\n5 oldest titles:" + color.END)
print(oldest_titles)

# Count the number of movies with 'Dracula' in the title
dracula_movies = titles_df[titles_df['title'].str.contains('Dracula', case=False, na=False)]
print(color.REVERSE + color.BOLD + "\nNumber of movies with 'Dracula' in the title:" + color.END, len(dracula_movies))

# Show the 10 most common titles
common_titles = titles_df['title'].value_counts().head(10)
print(color.REVERSE + color.BOLD + "\n10 most common titles:" + color.END)
print(common_titles.to_string())

# Find the first movie titled "Romeo and Juliet"
# Filter the DataFrame to get movies titled 'Romeo and Juliet'
romeo_and_juliet_movies = titles_df[titles_df['title'] == 'Romeo and Juliet']
# Sort the filtered DataFrame by the 'year' column
romeo_and_juliet_movie = romeo_and_juliet_movies.sort_values(by='year').head(1)
print(color.REVERSE + color.BOLD + "\nFirst movie titled 'Romeo and Juliet':" + color.END)
print(romeo_and_juliet_movie.to_string())

# List movies with 'Exorcist' in the title, sorted by year
exorcist_movies = titles_df[titles_df['title'].str.contains('Exorcist', case=False, na=False)].sort_values(by='year')
print(color.REVERSE + color.BOLD + "\nMovies with 'Exorcist' in the title, sorted by year:" + color.END)
print(exorcist_movies.to_string())

# Count the number of movies made in 1950
movies_1950 = len(titles_df[titles_df['year'] == 1950])
print(color.REVERSE + color.BOLD + "\nNumber of movies made in 1950:" + color.END, movies_1950)

# Count the number of movies made from 1950 to 1959 (inclusive)
movies_1950s = len(titles_df[(titles_df['year'] >= 1950) & (titles_df['year'] <= 1959)])
print(color.REVERSE + color.BOLD + "\nNumber of movies made from 1950 to 1959 (inclusive):" + color.END, movies_1950s)

# Group and count roles in 'The Godfather' trilogy
godfather_roles = elenco_df[elenco_df['title'].str.contains('The Godfather', case=False, na=False)]
role_counts = godfather_roles.groupby('character')['character'].count()
print(color.REVERSE + color.BOLD + "\nRoles in 'The Godfather' trilogy and their counts:" + color.END)
print(role_counts.to_string())

# Show the complete cast of 'Dracula' (1958), sorted by 'n'
dracula_1958_cast = elenco_df[(elenco_df['title'] == 'Dracula') & (elenco_df['year'] == 1958)].sort_values(by='n')
print(color.REVERSE + color.BOLD + "\nComplete cast of 'Dracula' (1958), sorted by 'n':" + color.END)
print(dracula_1958_cast)

# Count the number of roles for 'Bruce Wayne' as a protagonist
bruce_wayne_roles = elenco_df[
    elenco_df['character'].str.contains(r'(?i)^(?!waiter).*Bruce Wayne', case=False, na=False) 
    & (elenco_df['type'] == 'actor')
]
# As instruções são ambíguas, por um lado pedem protagonistas, mas pelo outro dizem que a personagem secundária Young Bruce Wayne também deve ser incluída. A linha abaixo deverá ser incluída para os papeis como protagonista.
# protagonist_roles = bruce_wayne_roles[bruce_wayne_roles['n'] == 1]
print(color.REVERSE + color.BOLD + "\nNumber of roles for 'Bruce Wayne' as a protagonist:" + color.END, len(bruce_wayne_roles)) # Usar a variável protagonis_roles se pretender protagonistas

# Count the total number of roles for 'Robert de Niro'
robert_de_niro_roles = elenco_df[elenco_df['name'] == 'Robert De Niro']
print(color.REVERSE + color.BOLD + "\nTotal number of roles for 'Robert de Niro':" + color.END, len(robert_de_niro_roles))

# List protagonist roles for 'Charlton Heston' in the 60s, sorted by year
charlton_heston_60s_roles = elenco_df[(elenco_df['name'] == 'Charlton Heston') & (elenco_df['type'] == 'actor') & (elenco_df['year'] >= 1960) & (elenco_df['year'] <= 1969)].sort_values(by='year', ascending=False)
print(color.REVERSE + color.BOLD + "\nProtagonist roles for 'Charlton Heston' in the 60s, sorted by year:" + color.END)
print(charlton_heston_60s_roles)

# Count the number of roles for actors in the 50s
actors_50s_roles = len(elenco_df[(elenco_df['type'] == 'actor') & (elenco_df['year'] >= 1950) & (elenco_df['year'] <= 1959)])
print(color.REVERSE + color.BOLD + "\nNumber of roles for actors in the 50s:" + color.END, actors_50s_roles)

# Count the number of roles for actresses in the 50s
actresses_50s_roles = len(elenco_df[(elenco_df['type'] == 'actress') & (elenco_df['year'] >= 1950) & (elenco_df['year'] <= 1959)])
print(color.REVERSE + color.BOLD + "\nNumber of roles for actresses in the 50s:" + color.END, actresses_50s_roles)


First 5 records of titles_df:
                                   title  year
0                                 Mahler  1974
1           Ogon, voda i... mednye truby  1968
2  Ana Nojoom bent alasherah wamotalagah  2014
3                      Malu de Bicicleta  2010
4             Nazareno Apostol: Boy Ahas  1989

First 5 records of elenco_df:
                  title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN

Number of records in titles_df: 230407
Number of records in elenco_df: 3564650

5 oldest titles:
                                                                    title  year
13229      


Number of roles for 'Bruce Wayne' as a protagonist: 46

Total number of roles for 'Robert de Niro': 103

Protagonist roles for 'Charlton Heston' in the 60s, sorted by year:
                               title  year             name   type                      character     n
944074                    Number One  1969  Charlton Heston  actor               Ron 'Cat' Catlan   1.0
944077            Planet of the Apes  1968  Charlton Heston  actor                  George Taylor   1.0
944050                  Counterpoint  1967  Charlton Heston  actor                   Lionel Evans   1.0
944120                    Will Penny  1967  Charlton Heston  actor                     Will Penny   1.0
944066                      Khartoum  1966  Charlton Heston  actor  Gen. Charles 'Chinese' Gordon   1.0
944068                  Major Dundee  1965  Charlton Heston  actor      Major Amos Charles Dundee   1.0
944085     The Agony and the Ecstasy  1965  Charlton Heston  actor                   Michelangelo 